name: Auto Post Pexels Photo to Telegram

on:
  schedule:
    # প্রতি ৩০ মিনিট পর পর রান করবে (ঘণ্টায় ২টি পোস্ট)
    - cron: '*/30 * * * *'
  workflow_dispatch: # ম্যানুয়ালি ক্লিক করে রান করার জন্য

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Execute Bot Script
        run: php bot.php
